fix: renames css link tag
error: It was raising error to load tailwind.css

cause: It was wrong file name in application layout.

solution: Changes call in `stylesheet_link_tag` from `:app` to `"application"`